theme: jekyll-theme-cayman
title: Kurtland Chua
description: I am a fourth-year undergraduate student at UC Berkeley, pursuing a degree in Electrical Engineering and Computer Sciences. I currently work in Prof. Sergey Levine's lab as an undergraduate researcher, working on model-based reinforcement learning with my mentors Roberto Calandra and Rowan McCallister.
